### ISSUE TITLE
Publish 0.4.0 to maven-central

### ISSUE THREAD

**Issue by DStranger** [circe/circe-golden#188]
Hi @zmccoy!

Looks like you've prepared `0.4.0` a while ago, would it be possible to publish it to maven-central?
Thanks in advance!

**Comment by adamnfish** [comment]
The early-semver change in circe 0.14.3 means updates like this in the rest of the ecosystem are important for teams trying to stay on top of version updates. Is there anything we can do to help get this version published?

Thank you!

**Comment by zmccoy** [comment]
Hi @adamnfish , the best way to help on this for circe-golden would be to get it updated and using the sbt-circe-org plugin which will enable us to release without issue, check mima, etc.  An example is here: 
 https://github.com/circe/circe-yaml/pull/348

**Comment by zarthross** [comment]
Shipping to maven now, sorry for the delay: https://github.com/circe/circe-golden/releases/tag/v0.4.0
