### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by guizmaii** [circe/circe-golden#32]
Hi Travis,

Is it possible for you to release a new version? The conflicts with the new version of `disciple-scalatests` are annoying and you already updated it in master.

Thanks.
Jules 🙂

**Comment by travisbrown** [comment]
Sure, it's on its way to Maven Central: https://github.com/circe/circe-golden/releases/tag/v0.2.0. :smile:

**Comment by guizmaii** [comment]
Thank you very much mate :)
