### ISSUE TITLE
When you encode something as `Option[Option[String]]` it can not properly decode

### ISSUE THREAD

**Issue by Fristi** [circe/circe-golden#36]
```
Expected: Right(VacancyProfileF(1683177f-5edb-4a9c-8f41-ca1b9e9ac631,Some(PartTime),Some(None),Some(O)))
Recieved: Right(VacancyProfileF(1683177f-5edb-4a9c-8f41-ca1b9e9ac631,Some(PartTime),None,Some(O)))
```

```
final case class VacancyProfileF[F[_]](
  id: VacancyProfileId,
  vacancyType: F[VacancyType],
  title: F[Option[NonEmptyString]],
  description: F[NonEmptyString]
)
```

Where `F` is set op `Option`

As you encode `Some(None)` and expect that.. but it's isomorphic to `None` which you get back

The use case is, when `F` is set to `cats.Id` it's an insert when it's set to `Option` it's an update where you choose to update specific fields by supplying a `Some` of something. When there is a `Option` inside this data structure, like `title` you'll get a `Option[Option[NonEmptyString]]`. Setting the title to nothing is `Some(None)`

**Comment by travisbrown** [comment]
This question comes up occasionally, and [this approach] is something I've used and recommended in the past. The issue isn't really circe-golden-specific, or even circe-testing-specific—it just becomes more obvious when you're doing this kind of laws checking.

**Comment by Fristi** [comment]
Good point, thanks for the approach on fixing that. I see no reason to keep this issue open
