### ISSUE TITLE
Generic case classes and Resources.inferName don't work

### ISSUE THREAD

**Issue by Fristi** [circe/circe-golden#37]
There is no file written when I:

```
checkAll("GoldenCodec[PlanResult[AppointmentDelivery]]", GoldenCodecTests[PlanResult[AppointmentDelivery]].unserializableGoldenCodec)
```

```
final case class PlanResult[A](appointment: A, succeeded: Boolean)
```

Guess `Resources.inferName` doesn't work with that type

**Comment by travisbrown** [comment]
Are you using [0.2.1](https://github.com/circe/circe-golden/releases/tag/v0.2.1)? I fixed something similar last week.

**Comment by Fristi** [comment]
It's fixed, upgraded :)
