### ISSUE TITLE
Unstable encoding of maps

### ISSUE THREAD

**Issue by fredfp** [circe/circe-golden#56]
This is a fantastic tool, it is however troublesome to use as soon as you are encoding maps because the order of keys in generated JSON objects is not stable (also see https://github.com/circe/circe/issues/556).

A way to work around this would be to allow passing an `io.circe.Printer` to use in `io.circe.testing.golden.GoldenCodecLaws.printJson` when building the `GoldenCodecTests` instance. This would allow users to pass `Printer.spaces2SortKeys` which would guarantee stable encoding and printing of json when maps are involved.

**Comment by travisbrown** [comment]
Definitely agreed that making the printer a parameter is a good idea!

**Comment by fredfp** [comment]
Ok, will try to find time for a PR
