### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by guizmaii** [circe/circe-golden#84]
Hi @travisbrown ,

Is it possible for you to release a new version, please? 
I hit this fixed-in-master problem: https://github.com/circe/circe-golden/pull/63

Thanks.
Jules 🙂

**Comment by yoohaemin** [comment]
Same here, I just hit the problem too. Would be very nice if you can release a new version soon.

**Comment by travisbrown** [comment]
Ah, sure, and my apologies, I thought I had done this already.

**Comment by travisbrown** [comment]
0.3.0 is out now, and will be the last release supporting ScalaCheck 1.14. I'll publish an 0.4.0 later today for ScalaCheck 1.15 (and release notes for both).

**Comment by guizmaii** [comment]
Thanks @travisbrown :)
